### ISSUE TITLE
The problem of unavailability of sensors and meters

### ISSUE THREAD

**Issue by MildaC** [andreondra/homeassistant-sermatec-inverter#33]
After updating Home Assistant Core to version 2023.5.2, there is an issue with the meters and the Riemann Integral Sum Sensor integration that retrieve states from the Sermatec integration. It seems that with zero input state, the meters and sensors are always unavailable at some time. I don't know if this is a bug in Home Assistant, or if the latest modification to the Sermatec integration may somehow be causing this. If I downgrade Home Assistant Core to version 2023.4.6, everything is fine. Can you please take a look at this? Thank you. I am attaching the log.

Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:344
First occurred: 08:43:42 (6 occurrences)
Last logged: 08:49:34

```
TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}) renders=34>' for attribute '_attr_native_value' in entity 'sensor.battery_power'
TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ (states('sensor.solar_inverter_grid_import') | round(0)) + (states('sensor.solar_inverter_battery_discharging_power') | round(0)) + (states('sensor.solar_inverter_pv_total_power') | round(0)) - (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_grid_export') | round(0)) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.solar_inverter_grid_import') | round(0)) + (states('sensor.solar_inverter_battery_discharging_power') | round(0)) + (states('sensor.solar_inverter_pv_total_power') | round(0)) - (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_grid_export') | round(0)) }}) renders=270>' for attribute '_attr_native_value' in entity 'sensor.okamzita_spotreba_domu'
TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}) renders=58>' for attribute '_attr_native_value' in entity 'sensor.battery_power'
TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ (states('sensor.solar_inverter_grid_import') | round(0)) + (states('sensor.solar_inverter_battery_discharging_power') | round(0)) + (states('sensor.solar_inverter_pv_total_power') | round(0)) - (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_grid_export') | round(0)) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.solar_inverter_grid_import') | round(0)) + (states('sensor.solar_inverter_battery_discharging_power') | round(0)) + (states('sensor.solar_inverter_pv_total_power') | round(0)) - (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_grid_export') | round(0)) }}) renders=320>' for attribute '_attr_native_value' in entity 'sensor.okamzita_spotreba_domu'
TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.solar_inverter_battery_charging_power') | round(0)) - (states('sensor.solar_inverter_battery_discharging_power') | round(0)) }}) renders=72>' for attribute '_attr_native_value' in entity 'sensor.battery_power'
```

**Comment by Akstef** [comment]
I am new in home assistant and I have no programmation skills. I use the sermatec integration in home assistant 2023.5.3 and after several minutes all sensors become unavailable. I need to reload the integration to have the data back again. Is it a bug or should I change something in my configuration?

**Comment by andreondra** [comment]
It could be a bug but also it can be caused by the inverter itself which sometimes stops responding to the requests.

**Comment by Akstef** [comment]
I don't think it is the inverter which stops responding. If I am working one hour to configure my system and I am connected to it, the sensors never stop. If only my smartphone is used to check from time to time how the system react, after 20 to 30 minutes of inactivity, the sensors stop working. As soon as I reload the integration, all sensors are back. Can you integrate an auto reload fonction when the sensors become unavailable?

**Comment by MBoronNeotreks** [comment]
Maybe adding more try/except or specifying call timeouts to the `sermatec-inverter` project could help.
I see these are used only for the `connect` function.
But I checked that project just briefly and I'm not a Python programmer.

**Comment by mboron** [comment]
Maybe adding more try/except or specifying call timeouts to the `sermatec-inverter` project could help.
I see these are used only for the `connect` function.
But I checked that project just briefly and I'm not a Python programmer.
Btw. I'm facing the very same issue.

**Comment by mathieupotier** [comment]
having few logs in my instance that could explain the error :
```
2023-05-25 19:43:43.100 ERROR (MainThread) [custom_components.sermatec_inverter.sensor] Error fetching Sermatec data: Can't connect to the inverter.
2023-05-25 19:43:43.103 ERROR (MainThread) [homeassistant.components.sensor] sermatec_inverter: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 444, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 95, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 237, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/sermatec_inverter/sensor.py", line 525, in _handle_coordinator_update
    self._attr_native_value = self.coordinator.data[self.dict_key]
TypeError: 'NoneType' object is not subscriptable
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/sermatec_inverter/sensor.py", line 525, in _handle_coordinator_update
    self._attr_native_value = self.coordinator.data[self.dict_key]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mathieupotier** [comment]
@Akstef the inverter sometimes stop responding, having the same issue on another project.

I assume that the connected socket die, and need to reconnect to the inverter to have queries and response back again.
But sometimes for some reason, the inverter drops the TCP socket... 🤷‍♂️ 
Need to be taken into account when developping an inverter client...
But the protocol itself is quite magic ... already amazing to have a home assistant plugin for that one ... cheers 🍾 @andreondra

**Comment by mathieupotier** [comment]
Created an automation in my HA instance to try to reload the integration automatically (better thazn nothing) ... but sometimes, it just fail endlessly ... 🤷‍♂️ 

```yaml
alias: Reload auto Sermatec
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.solar_inverter_inverter_working_mode
      - sensor.solar_inverter_battery_state
      - sensor.sermatec_solar_inverter
    to: unavailable
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - platform: state
    entity_id:
      - sensor.solar_inverter_inverter_working_mode
      - sensor.solar_inverter_battery_state
      - sensor.sermatec_solar_inverter
    to: unknown
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition: []
action:
  - repeat:
      while:
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.sermatec_solar_inverter
              state: unknown
              for:
                hours: 0
                minutes: 0
                seconds: 0
            - condition: state
              entity_id: sensor.solar_inverter_battery_state
              state: unknown
              for:
                hours: 0
                minutes: 0
                seconds: 0
            - condition: state
              entity_id: sensor.solar_inverter_inverter_working_mode
              state: unknown
              for:
                hours: 0
                minutes: 0
                seconds: 0
            - condition: state
              entity_id: sensor.sermatec_solar_inverter
              state: unavailable
              for:
                hours: 0
                minutes: 0
                seconds: 0
            - condition: state
              entity_id: sensor.solar_inverter_battery_state
              state: unavailable
              for:
                hours: 0
                minutes: 0
                seconds: 0
            - condition: state
              entity_id: sensor.solar_inverter_inverter_working_mode
              state: unavailable
              for:
                hours: 0
                minutes: 0
                seconds: 0
      sequence:
        - service: homeassistant.reload_config_entry
          data: {}
          target:
            entity_id: sensor.sermatec_solar_inverter
        - delay:
            hours: 0
            minutes: 0
            seconds: 15
            milliseconds: 0
mode: single
```
